packages/learning-package-one/src/learning-package-one.ts
=> fix: add number

packages/learning-package-one/package-lock.json, packages/learning-package-one/src/learning-package-one.ts, packages/learning-package-two/package-lock.json
=> feat(package-one): update feature

package.json, packages/learning-package-one/package-lock.json, packages/learning-package-one/src/learning-package-one.ts, packages/learning-package-two/package-lock.json
=> feat: update

packages/learning-package-two/README.md, packages/learning-package-two/src/learning-package-two.ts
=> feat(readme): new commit

.github/workflows/nodejs_publish.yml
=> feat(nodejs_publish.yml): new publish

.github/workflows/nodejs_publish.yml, packages/learning-package-one/README.md
=> feat(readme): readme

.github/workflows/nodejs_publish.yml
=> feat(test): test

.github/workflows/nodejs_publish.yml
=> feat(test): testing

.github/workflows/nodejs_publish.yml
=> feat(testing): test

.github/workflows/nodejs_publish.yml
=> feat(test): new test

.github/workflows/nodejs_publish.yml
=> feat(nodejs_publish.yml): new test

.github/workflows/nodejs_publish.yml
=> feat(checkout): checkout

.github/workflows/nodejs_publish.yml
=> feat(new): new

.github/workflows/nodejs_publish.yml
=> feat(again): again

.github/workflows/nodejs_publish.yml
=> feat(update): update

package.json
=> fix(all): all

.github/workflows/nodejs_publish.yml, lerna.json, packages/learning-package-one/README.md
=> feat(New script): new script

lerna.json
=> fix(README): readme changes

.github/workflows/nodejs_publish.yml, packages/learning-package-one/README.md, packages/learning-package-one/package-lock.json, packages/learning-package-two/package-lock.json
=> fix(nodejs_publish.yml): new update

.github/workflows/nodejs_publish.yml, packages/learning-package-one/README.md, packages/learning-package-one/package-lock.json, packages/learning-package-two/package-lock.json
=> feat(nodejs_publish.yml): update publish file

.github/workflows/nodejs_CI.yml, .github/workflows/nodejs_publish.yml, .github/workflows/nodejs_release.yml, lerna.json, packages/learning-package-one/README.md, packages/learning-package-one/package-lock.json, packages/learning-package-two/package-lock.json
=> feat(nodejs_release.yml): create release file

.github/workflows/nodejs_CI.yml, .github/workflows/nodejs_publish.yml, .github/workflows/nodejs_release.yml
=> chore(nodejs_release.yml): create release of last tag using GitHub Actions

.github/workflows/nodejs_CI.yml, .github/workflows/nodejs_publish.yml
=> chore(nodejs_publish.yml): migrate CD from travis to GitHub Actions

packages/learning-package-one/package-lock.json, packages/learning-package-two/package-lock.json
=> feat(readme): readme again

packages/learning-package-one/package-lock.json, packages/learning-package-one/src/index.ts, packages/learning-package-two/package-lock.json
=> feat(newV): newV

package.json
=> feat(aa): aa
